# src/main/resources/application.properties
spring.application.name=api-integration-hub
server.port=${PORT:8080}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

github.token=${GITHUB_TOKEN:}
openweather.api.key=${OPENWEATHER_API_KEY:}
